version: "3.8"

services:
  auth:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}

networks:
  default:
    external:
      name: tools_default
