"""Create user table

Revision ID: 3ca537d08990
Revises:
Create Date: 2021-01-17 19:51:37.897490

"""
import sqlalchemy as sa

from alembic import op  # type: ignore
from app.models.user import GUID

# revision identifiers, used by Alembic.
revision = "3ca537d08990"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usertable",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=72), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usertable_email"), "usertable", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usertable_email"), table_name="usertable")
    op.drop_table("usertable")
    # ### end Alembic commands ###
