name: DEPLOY

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Copy compose file to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "docker-compose.prod.yml"
          target: "~/auth"
      
      - name: Copy scripts folder to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "scripts/"
          target: "~/auth/scripts/"

      - name: Restart docker-compose
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker login -u ${{ github.repository_owner }} -p ${{ secrets.CR_PAT }} ghcr.io
            docker-compose -f ~/auth/docker-compose.prod.yml pull
            docker-compose -f ~/auth/docker-compose.prod.yml up -d
